In [1]:
#Import dependencies
import requests
from bs4 import BeautifulSoup
import pandas as pd
import random
import time

In [2]:
jobs_title = [
    #Data
    "Data Analyst",
    "Data Engineer",
    "Analytics Engineer",
    "Machine Learning Engineer",
    
    # 3 משרות פיתוח (Software Development)
    "Python Developer",
    "Full Stack Developer",
    "Backend Developer",
    
    # 2 משרות QA
    "QA Engineer",
    "Automation Engineer",
    
    # 1 משרה של מנהל מוצר
    "Product Manager"
]  # Job title
location = "Israel"  # Job location
start = 0  # Starting point for pagination
end = 50

In [3]:
#Create an empty list to store the job postings
id_list = []

In [4]:
  
for start in range(0,400,10):

    # Construct the URL for LinkedIn job search
    list_url = f"https://www.linkedin.com/jobs-guest/jobs/api/seeMoreJobPostings/search?location={location}&f_E=2%2C1%2C3&start={start}&f_TPR=r86400&pageNum=0"

    # Send a GET request to the URL and store the response
    response = requests.get(list_url)

    #Get the HTML, parse the response and find all list items(jobs postings)
    list_data = response.text
    list_soup = BeautifulSoup(list_data, "html.parser")
    page_jobs = list_soup.find_all("li")
    if not page_jobs:
        break
    for job in page_jobs:
        base_card_div = job.find("div", {"class": "base-card"})
        if not base_card_div:
            break
        job_id = base_card_div.get("data-entity-urn").split(":")[3]
        id_list.append(job_id)
    print(f"{len(id_list)} jobs extracted from LinkedIn")
    

    time.sleep(random.uniform(0.5,2))

10 jobs extracted from LinkedIn
20 jobs extracted from LinkedIn
30 jobs extracted from LinkedIn
40 jobs extracted from LinkedIn
50 jobs extracted from LinkedIn
60 jobs extracted from LinkedIn
70 jobs extracted from LinkedIn
80 jobs extracted from LinkedIn
90 jobs extracted from LinkedIn
100 jobs extracted from LinkedIn
110 jobs extracted from LinkedIn
120 jobs extracted from LinkedIn
130 jobs extracted from LinkedIn
140 jobs extracted from LinkedIn
150 jobs extracted from LinkedIn
160 jobs extracted from LinkedIn
170 jobs extracted from LinkedIn
180 jobs extracted from LinkedIn
190 jobs extracted from LinkedIn
200 jobs extracted from LinkedIn
210 jobs extracted from LinkedIn
220 jobs extracted from LinkedIn
230 jobs extracted from LinkedIn
240 jobs extracted from LinkedIn
250 jobs extracted from LinkedIn
260 jobs extracted from LinkedIn
269 jobs extracted from LinkedIn
279 jobs extracted from LinkedIn
289 jobs extracted from LinkedIn
299 jobs extracted from LinkedIn
302 jobs extracted from LinkedIn

In [5]:
id_list

['4370963330',
 '4383805162',
 '4382820819',
 '4383724471',
 '4214614545',
 '4382466446',
 '4383786827',
 '4382561327',
 '4383835754',
 '4384103280',
 '4382091725',
 '4383796982',
 '4381514993',
 '4382480812',
 '4383840707',
 '4377871605',
 '4382076250',
 '4384175338',
 '4383308880',
 '4382502573',
 '4351762567',
 '4382473162',
 '4383837784',
 '4382893514',
 '4384116842',
 '4383836454',
 '4383844464',
 '4232901222',
 '4384193582',
 '4384149706',
 '4366369464',
 '4382896536',
 '4364671319',
 '4381608552',
 '4382557972',
 '4383800946',
 '4382520253',
 '4383758388',
 '4382570766',
 '4384308062',
 '4382570766',
 '4384102322',
 '4375519661',
 '4372846093',
 '4383851043',
 '4375153638',
 '4382534603',
 '4382070221',
 '4384161127',
 '4382532679',
 '4384147311',
 '4384130884',
 '4366367063',
 '4373448873',
 '4382889845',
 '4383203314',
 '4384174666',
 '4382897550',
 '4350253782',
 '4384180970',
 '4381833685',
 '4383785875',
 '4382577115',
 '4324275243',
 '4384179489',
 '4383858048',
 '4382481710',
 '4382575263',
 '4382562669',
 '4382087057',
 '4374713618',
 '4382577443',
 '4382083618',
 '4373230283',
 '4383846964',
 '4376754137',
 '4383761458',
 '4366148772',
 '4382883834',
 '4382068903',
 '4383804709',
 '4382854894',
 '4383800344',
 '4372855592',
 '4370135863',
 '4383771155',
 '4383805061',
 '4384154458',
 '4382549822',
 '4384187018',
 '4382549822',
 '4384187018',
 '4382893355',
 '4344351134',
 '4384117813',
 '4383848522',
 '4383852115',
 '4382569716',
 '4366224617',
 '4384179846',
 '4382496780',
 '4370147267',
 '4384167164',
 '4337880474',
 '4383829954',
 '4382069668',
 '4384163387',
 '4384145589',
 '4383753447',
 '4382876128',
 '4382562731',
 '4382056955',
 '4382844389',
 '4362123708',
 '4343741933',
 '4382838952',
 '4381499987',
 '4384181157',
 '4382067872',
 '4384176862',
 '4373556417',
 '4382568827',
 '4382560332',
 '4355783706',
 '4384153920',
 '4384131963',
 '4384153382',
 '4365840113',
 '4383791205',
 '4382079847',
 '4314754099',
 '4382063699',
 '4384168841',
 '4383835997',
 '4356230334',
 '4383783378',
 '4383314452',
 '4384165683',
 '4384176020',
 '4383762260',
 '4374114654',
 '4345715403',
 '4382565131',
 '4361223828',
 '4327675365',
 '4384170435',
 '4300549819',
 '4279474200',
 '4382077565',
 '4384194396',
 '4383750781',
 '4382093110',
 '4361967532',
 '4374173139',
 '4383766395',
 '4373972716',
 '4355693771',
 '4382083435',
 '4372586159',
 '4384154379',
 '4384154379',
 '4321429779',
 '4382424490',
 '4383209080',
 '4356211502',
 '4382895729',
 '4382576274',
 '4383852209',
 '4384148806',
 '4371438296',
 '4320117612',
 '4365840110',
 '4382575041',
 '4384152231',
 '4382074485',
 '4384156938',
 '4382061707',
 '4382055478',
 '4327685310',
 '4381262319',
 '4382895773',
 '4382448052',
 '4383757587',
 '4357461769',
 '4372873623',
 '4382809483',
 '4372866779',
 '4365990613',
 '4382807535',
 '4303354093',
 '4303354093',
 '4384140761',
 '4330524630',
 '4384179070',
 '4365835677',
 '4382499642',
 '4382499629',
 '4382813140',
 '4314747370',
 '4365047281',
 '4343804134',
 '4373994114',
 '4384173367',
 '4329840290',
 '4382569350',
 '4382863906',
 '4383771235',
 '4382458067',
 '4330474609',
 '4372880530',
 '4367180272',
 '4351325128',
 '4279470693',
 '4373045907',
 '4384151198',
 '4382572812',
 '4279467993',
 '4365960167',
 '4383765060',
 '4383210357',
 '4383207031',
 '4384120554',
 '4343994237',
 '4373301752',
 '4365805806',
 '4320492995',
 '4363153993',
 '4382555391',
 '4382567657',
 '4343863641',
 '4373989608',
 '4383771234',
 '4372871123',
 '4327815268',
 '4382862188',
 '4330265454',
 '4371962808',
 '4382558768',
 '4383818454',
 '4384165875',
 '4382574650',
 '4384162927',
 '4364787314',
 '4383818454',
 '4330058035',
 '4368111632',
 '4330584506',
 '4330245667',
 '4382073324',
 '4364789954',
 '4382815065',
 '4384152145',
 '4384188667',
 '4384190310',
 '4384185467',
 '4321534311',
 '4382557945',
 '4344031311',
 '4372516852',
 '4384187760',
 '4279476059',
 '4382076705',
 '4365835676',
 '4384181893',
 '4363153789',
 '4356192238',
 '4382575611',
 '4382576504',
 '4314757333',
 '4382578339',
 '4281329861',
 '4146380988',
 '4382924581',
 '4279474162',
 '4382062750',
 '4384163797',
 '4356201549',
 '4382095939',
 '4356153027',
 '4279474162',
 '4382062750',
 '4384163797',
 '4356201549',
 '4382095939',
 '4356153027',
 '4382437197',
 '4384167278',
 '4384164351',
 '4343893419',
 '4366041796',
 '4355976179',
 '4371963875',
 '4382888451',
 '4382056196',
 '4383767557',
 '4356211518',
 '4382074296',
 '4382077045',
 '4382586127',
 '4366039403',
 '4382855603',
 '4384126768']

In [6]:
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36",
    "Accept-Language": "en-US,en;q=0.9",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8",
    "Referer": "https://www.linkedin.com/jobs/search?keywords=Data%20Analyst", # שינוי Referer
    "Upgrade-Insecure-Requests": "1"
}

# Initialize an empty list to store job information
job_list = []
# Loop through the list of job IDs and get each URL
for job_id in id_list:
    # Construct the URL for each job using the job ID
    
    job_url = f"https://www.linkedin.com/jobs-guest/jobs/api/jobPosting/{job_id}"
    
    # Send a GET request to the job URL and parse the reponse
    try:
        job_response = requests.get(job_url, headers=headers)
        
        if job_response.status_code != 200:
            print(f"Error {job_response.status_code} for job {job_id[0]}")
            if job_response.status_code == 429:
                print("to many requests/ 5 minutes sleep")
                time.sleep(300) # עצירה ל-5 דקות אם נחסמנו
            continue
        print(job_response.status_code)
        job_soup = BeautifulSoup(job_response.text, "html.parser")
        
        # Create a dictionary to store job details
        job_post = {}
        
        # Try to extract and store the job title
        try:
            job_post["job_title"] = job_soup.find("h2", {"class":"top-card-layout__title font-sans text-lg papabear:text-xl font-bold leading-open text-color-text mb-0 topcard__title"}).text.strip()
        except:
            job_post["job_title"] = None
            
        # Try to extract and store the company name
        try:
            job_post["company_name"] = job_soup.find("a", {"class": "topcard__org-name-link topcard__flavor--black-link"}).text.strip()
        except:
            job_post["company_name"] = None
            
        
        # אנחנו מחפשים את ה-span השני בתוך ה-row של ה-flavor
        try:
        # בדרך כלל האינדקס 0 הוא המיקום (במקרה הזה Petah Tikva)
            job_post["location"] = job_soup.find_all("span", {"class": "topcard__flavor topcard__flavor--bullet"})[0].text.strip()
        except:
            job_post["location"] = None
            
        # Try to extract and store the time posted
        try:
            job_post["time_posted"] = job_soup.find("span", {"class": "posted-time-ago__text topcard__flavor--metadata"}).text.strip()
        except:
            job_post["time_posted"] = None
            
        # Try to extract and store the number of applicants
        try:
            job_post["num_applicants"] = job_soup.find("span", {"class": "num-applicants__caption topcard__flavor--metadata topcard__flavor--bullet"}).text.strip()
        except:
            job_post["num_applicants"] = None
        try:
            job_description_div = job_soup.find('div', class_='description__text--rich')
            job_post["description_text"] = job_description_div.get_text(separator='\n', strip=True)
        except:
            job_post["description_text"] = None
            
        job_post["URL"] = job_url
            
        # Append the job details to the job_list
        job_list.append(job_post)

    except Exception as e:
        print(f"Request failed: {e}")
        time.sleep(10)
        continue

    # המתנה ארוכה יותר ומשתנה
    time.sleep(random.uniform(5, 12))

200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200

In [7]:
#Check if the list contains all the desired data
job_list

[{'job_title': 'Financial Analyst',
  'company_name': 'Deloitte',
  'location': 'Tel Aviv District, Israel',
  'time_posted': None,
  'num_applicants': None,
  'description_text': 'Deloitte is looking for Financial Analyst. Overall responsibility for the management, control, and support of client projects, focusing on the financial aspects of projects and clients, while delivering a range of services in reporting, controls, accounts receivable, and budgeting. The role involves working with senior managers and diverse stakeholders and requires strong attention to detail. Review and control basic pricing prior to submission in the organization’s systems. Update tracking of data and engagement agreements (SOWs). Create a work breakdown structure (WBS) in the SWIFT system and track project financial data. Reconcile project data against SWIFT, monitor account status, and other financial targets. Provide periodic reporting to senior leadership (Partner/Principal/Managing Director—PPMD) on project metrics: profitability, revenue, expenses, days sales outstanding (DSO). Set the cadence for standard financial reports, including analysis for senior leadership. Track and maintain project budgets and forecasts in line with organizational requirements. Prepare invoices; report on and track collections; manage project billing, including handling intercompany charges. Review and provide recommendations to improve DSO; monitor profitability and financial efficiency throughout the project lifecycle. Report final financial status to project managers; perform reconciliations; and handle requests to open, update, and close projects in the SWIFT system.\nRequirements-\nRelevant academic degree / bookkeeping qualification (e.g., Business Administration, Economics) an advantage\nExperience working with senior stakeholders and multiple interfaces - a significant advantage\nThoroughness, attention to details, and ability to work independently and as part of a team\nHigh proficiency in Excel and enterprise financial systems (SAP — an advantage)\nAbility to manage multiple tasks in parallel, meet deadlines, and work under pressure\nHigh level of English — a significant advantage\nShow more\nShow less',
  'URL': 'https://www.linkedin.com/jobs-guest/jobs/api/jobPosting/4370963330'},
 {'job_title': 'Sales Development Representative',
  'company_name': 'Hud',
  'location': 'Tel Aviv-Yafo, Tel Aviv District, Israel',
  'time_posted': None,
  'num_applicants': None,
  'description_text': 'Job Description\nAbout The Role\nHud is looking for a Sales Development Representative (SDR) to join our GTM team and help drive pipeline growth in global markets. This role sits at the front line of our go-to-market motion and plays a critical role in opening new opportunities with technical buyers and senior stakeholders.\nThis is a\nhands-on, high-pace role\nfor someone who enjoys outbound, is motivated by results, and wants to grow into a closing or leadership position in a fast-moving startup environment.\nExperience\nJob Requirements\n1–3 years of experience in B2B SaaS sales, SDR, or a similar outbound-focused role\nProven ability to generate pipeline through outbound prospecting (email, LinkedIn, calls, account-based outreach)\nExperience engaging technical buyers and senior managers in initial conversations\nStrong qualification skills and ability to identify real buying signals\nExperience working with CRM and pipeline generation tools and maintaining accurate activity and pipeline data\nComfortable working across global markets\nComfortable with high-volume, phone-first outbound, and confident handling initial objections and pushback\nCurious and hands-on with AI tools, using them to improve prospecting, research, messaging, and productivity\nJob Responsibilities\nExcellence Mindset\nStrong hunter mentality and motivation to win\nHigh activity, high ownership, and accountability for outcomes\nEnergized by outbound conversations, resilient to rejection, and motivated to push past objections\nCurious, coachable, and eager to improve quickly\nThrives in fast-paced, high-expectation environments\nOrganized, disciplined, and focused on execution\nTeam-oriented, with strong collaboration with AEs and Marketing\nJob Benefits\nBonus Points\nExperience in prospecting or selling to Enterprise or large mid-market accounts\nBackground in developer tools, infrastructure, or technical products\nExperience in early-stage or high-growth startups\nRequirements\nBased in Tel Aviv – work from the office\nAbility to work flexible hours, including overlap with US time zones\nComfortable working in a fast-paced startup environment\nStrong written and verbal communication skills in English\nShow more\nShow less',
  'URL': 'https://www.linkedin.com/jobs-guest/jobs/api/jobPosting/4383805162'},
 {'job_title': 'Web Application Developers',
  'company_name': 'GoodWork Environmental Jobs',
  'location': 'Or Akiva, Haifa District, Israel',
  'time_posted': None,
  'num_applicants': '53 applicants',
  'description_text': 'Web application development\nPosition:\nWeb Application Developer\nOrganization:\nBirds Canada\nLocation:\nThis role may be performed remotely from anywhere in Canada or from one of our office locations (Port Rowan, ON, or Sackville, NB). Hybrid arrangements also available to support accessibility and work-life balance.\nBirds Canada is the country’s leading national organization dedicated to bird conservation. Our dedicated team of over 100 staff works alongside thousands of committed volunteers to support bird research and conservation. Birds Canada is a collaborative, values-driven organization that supports flexibility and well-being while tackling important conservation challenges.\nBirds Canada’s Data Science and Technology branch maintains two internationally recognized conservation technology platforms\nNatureCounts\n(naturecounts.ca) and the\nMotus Wildlife Tracking System\n(motus.org)\n.\nThese tools support hundreds of research and monitoring projects across more than 400 institutions, enabling the collection, management, and sharing of thousands of datasets representing nearly 10 billion observations. These data have contributed to more than 4,500 scientific publications. These data and tools are instrumental to the successful implementation of the Kunming-Montreal Global Biodiversity Framework and Canada’s 2030 Nature Strategy, and for solving applied conservation challenges from local to global scales (see Evidence of Success and this video).\nPOSITION CONCEPT\nBirds Canada is hiring one to two software developers to support the development and maintenance of software applications used for the collection, management and exploration of bird population and tracking data through the NatureCounts platform (naturecounts.ca) and Motus Wildlife Tracking Network (motus.org).\nThe Core Tech Stack Used Includes\nVersioning and Task Tracking\n: GitHub\nDatabase\n: Microsoft SQL Server\nBackend:\nJava, Geoserver\nFront End\nJavaScript, HTML, CSS, Bootstrap, Mapbox, Leaflet, Highcharts\nLegacy Java Server Pages (JSP)\nReact\nThe initial focus of this position will be primarily front-end development of data exploration and mapping products (e.g https://naturecounts.ca/nc/default/explore.jsp) and species accounts (e.g. https://naturecounts.ca/nc/socb-epoc/species.jsp?sp=canwar#distribution).\nEMPLOYMENT DETAILS\nReporting to the Associate Director, Data Science and Technology, this is a two-year, full-time contract position, with strong likelihood of renewal dependant on funding availability. This role may be performed remotely from anywhere in Canada or from one of our office locations (Port Rowan, ON, or Sackville, NB). Hybrid arrangements also available to support accessibility and work-life balance. This posting is for an existing vacancy.\nSALARY\nThis role offers a starting salary range of $56,987 - $74,084, with the final salary determined based on relevant experience and aligned with internal pay equity practices.\nTotal Compensation And Benefits\nBirds Canada offers a competitive starting wage with predictable annual increases, 20 days of vacation and 12 personal health days per year (prorated based on start date and contract duration), paid days off between Boxing Day and New Year’s Day, and observance of all statutory holidays, including the National Day of Truth and Reconciliation. After 12 months, employees receive 5% RRSP matching through Canada Life.\nWe also offer a primarily employer-paid extended health and dental benefits package - including disability, life insurance, vision care, travel insurance, and an Employee/Family Assistance Plan, as well as access to exclusive employee discounts through select outdoor and conservation-focused partners.\nBirds Canada consistently sees strong employee wellness outcomes and high Employee Net Promoter Scores, reflecting a workplace where people feel supported, engaged, and proud of the work they do.\nDuties And Responsibilities\nThe developer, in conjunction with Data Science & Technology staff, may take part in any of the following tasks:\nDevelop responsive, web-based data visualization and exploration tools, including interactive maps, tables and graphs.\nOptimize performance and speed of data visualization and download tools.\nManage workflows and code versioning through git and GitHub.\nMaintain appropriate documentation on applications.\nEnsure applications maintain appropriate levels of security and cybersecurity.\nEDUCATION\nBSc or technical degree in computer sciences, or a BSc in life sciences, with pertinent experience in web application development.\nRequired Knowledge, Skills And Experience\nDemonstrated experience in front end programming languages: HTML, CSS, Bootstrap, Java servlets/JSPs, Geoserver, Mapbox and React.\nFamiliarity with Java and SQL and ability to read existing code in these languages.\nExperience with geospatial software and web applications (ArcGIS, Geoserver, Leaflet, SQL Server Spatial Data etc.) would be an asset.\nFamiliarity working with git version control and application deployment.\nKnowledge or interest in ecology (birds, in particular) and conservation.\nEnglish mandatory, French and/or Spanish would be assets.\nWorking with and optimizing large datasets would be an asset.\nTO APPLY\nPlease submit your resume along with a covering letter outlining how your experience makes you the ideal candidate for this role via the Birds Canada Online Job Portal by March 31 at 12pm EST. Please note that applicants must be legally authorized to work in Canada at the time of application. Birds Canada will provide accommodation throughout the recruitment, selection, and/or assessment process to applicants with disabilities.\nPlease mention you saw this at\nGoodWork.ca\n.\nAt Birds Canada, we are committed to fostering a culture that values Indigenous Engagement and Reconciliation, and Inclusivity, Diversity, Equity, and Accessibility, as integral approaches that shape all that we do in our organization and for nature (read our full commitment to inclusion\nat this LINK\n). We oppose prejudice, bigotry, and discrimination, and aim to ensure that people of all backgrounds, identities, abilities, and experiences feel a sense of belonging and can participate in protecting wild birds and their habitats.\nWe are actively seeking to improve our ability to reach all candidates with our job postings. Applicants belonging to racialized groups, who identify as Indigenous, 2SLGBTQIA+, and/or who have a disability, are therefore welcome to mention this in their cover letter, if they feel comfortable, although this is not a requirement.\nShow more\nShow less',
  'URL': 'https://www.linkedin.com/jobs-guest/jobs/api/jobPosting/4382820819'},
 {'job_title': 'Client Success Representative',
  'company_name': 'Jobgether',
  'location': 'Israel',
  'time_posted': None,
  'num_applicants': '51 applicants',
  'description_text': "This position is posted by Jobgether on behalf of a partner company. We are currently looking for a Client Success Representative in Israel.\nIn this role, you will be the primary point of contact for clients, ensuring their success and satisfaction with the services provided. You will build strong, lasting relationships, proactively address challenges, and help clients achieve their objectives through timely and effective support. The position involves managing a diverse set of tasks, from administrative operations to client communications, in a fast-paced environment. You will collaborate closely with internal teams to deliver seamless experiences, identify growth opportunities, and contribute to strategic initiatives. This role offers an enriching environment with opportunities for professional growth, exposure to multiple industries, and the chance to make a tangible impact on client success. It is ideal for someone who thrives on problem-solving, relationship-building, and delivering exceptional service.\nAccountabilities\nBuild and maintain strong, long-term relationships with clients, serving as a trusted advisor.\nEnsure timely and successful delivery of solutions aligned with client needs and objectives.\nCommunicate clearly with clients and internal teams on progress, updates, and any escalations.\nIdentify and develop opportunities for growth within assigned accounts, collaborating with sales teams to achieve goals.\nAssist with complex client requests, issue resolution, and escalation management.\nSupport internal operations through tasks such as data entry, system updates, and schedule coordination.\nAdvocate for client needs while maintaining alignment with organizational processes and objectives.\nRequirements\nProven experience managing client relationships, preferably in client success, hospitality, or sales roles.\nExcellent communication, interpersonal, and problem-solving skills.\nAbility to handle multiple tasks with attention to detail, managing priorities effectively in a fast-paced environment.\nEmpathetic understanding of client needs and the ability to provide thoughtful, proactive solutions.\nStrong organizational skills and adaptability to changing requirements.\nExperience working collaboratively with internal teams to drive client satisfaction and business outcomes.\nProficiency in English, both written and spoken.\nBenefits\nFully remote work with flexibility to manage your schedule.\nOpportunity to work in a supportive, inclusive, and collaborative team environment.\nExposure to a variety of industries and client types, fostering professional growth.\nAccess to learning and development opportunities to enhance skills and career progression.\nA company culture that values employee satisfaction, recognition, and meaningful contributions.\nWhy Apply Through Jobgether?\nWe use an\nAI-powered matching process\nto ensure your application is reviewed quickly, objectively, and fairly against the role's core requirements. Our system identifies the top-fitting candidates, and this shortlist is then shared directly with the hiring company. The final decision and next steps (interviews, assessments) are managed by their internal team.\nWe appreciate your interest and wish you the best!\nWhy Apply Through Jobgether?\nData Privacy Notice:\nBy submitting your application, you acknowledge that Jobgether will process your personal data to evaluate your candidacy and share relevant information with the hiring employer. This processing is based on legitimate interest and pre-contractual measures under applicable data protection laws (including GDPR). You may exercise your rights (access, rectification, erasure, objection) at any time.\nWe may use artificial intelligence (AI) tools to support parts of the hiring process, such as reviewing applications, analyzing resumes, or assessing responses. These tools assist our recruitment team but do not replace human judgment. Final hiring decisions are ultimately made by humans. If you would like more information about how your data is processed, please contact us.\nShow more\nShow less",
  'URL': 'https://www.linkedin.com/jobs-guest/jobs/api/jobPosting/4383724471'},
 {'job_title': 'Junior Technical Support Engineer (fresh graduate)',
  'company_name': 'OPSWAT',
  'location': 'Petah Tikva, Center District, Israel',
  'time_posted': None,
  'num_applicants': None,

In [8]:
# Create a pandas DataFrame using the list of job dictionaries 'job_list'
jobs_df = pd.DataFrame(job_list)
jobs_df

,job_title,company_name,location,time_posted,num_applicants,description_text,URL
0,Financial Analyst,Deloitte,"Tel Aviv District, Israel",None,None,Deloitte is looking for Financial Analyst. Ove...,https://www.linkedin.com/jobs-guest/jobs/api/j...
1,Sales Development Representative,Hud,"Tel Aviv-Yafo, Tel Aviv District, Israel",None,None,Job Description\nAbout The Role\nHud is lookin...,https://www.linkedin.com/jobs-guest/jobs/api/j...
2,Web Application Developers,GoodWork Environmental Jobs,"Or Akiva, Haifa District, Israel",None,53 applicants,Web application development\nPosition:\nWeb Ap...,https://www.linkedin.com/jobs-guest/jobs/api/j...
3,Client Success Representative,Jobgether,Israel,None,51 applicants,This position is posted by Jobgether on behalf...,https://www.linkedin.com/jobs-guest/jobs/api/j...
4,Junior Technical Support Engineer (fresh gradu...,OPSWAT,"Petah Tikva, Center District, Israel",None,None,"OPSWAT, a global leader in IT, OT, and ICS cri...",https://www.linkedin.com/jobs-guest/jobs/api/j...
...,...,...,...,...,...,...,...
297,Sr/ Principal Backend Developer - Cloud Applic...,Palo Alto Networks,"Tel Aviv-Yafo, Tel Aviv District, Israel",1 day ago,None,"Our Mission\nAt Palo Alto Networks®, we’re uni...",https://www.linkedin.com/jobs-guest/jobs/api/j...
298,SAP SD / OTC Implementer,SQLink Group,"Petah Tikva, Center District, Israel",None,None,We are recruiting an\nSAP SD / OTC Implementer...,https://www.linkedin.com/jobs-guest/jobs/api/j...
299,Experienced Algorithm Engineer for Priority Se...,Mobileye,"Haifa District, Israel",None,None,Join Mobileye's REM (Road Experience Managemen...,https://www.linkedin.com/jobs-guest/jobs/api/j...
300,Senior SW Technical Lead,ForSight Robotics,"Caesarea, Haifa District, Israel",None,None,Who we are\nWe are here to improve lives by re...,https://www.linkedin.com/jobs-guest/jobs/api/j...
301,DevEx Engineer,Orca Security,"Tel Aviv-Yafo, Tel Aviv District, Israel",None,None,"Big Ideas. Real People.\nAt Orca, in the right...",https://www.linkedin.com/jobs-guest/jobs/api/j...

In [9]:
from datetime import date

# יצירת תאריך של היום בפורמט YYYY-MM-DD
today = date.today()

# הוספת העמודה ל-DataFrame
jobs_df['search_date'] = today

# הצגת התוצאה
print(jobs_df.head())

                                           job_title  \
0                                  Financial Analyst
1                   Sales Development Representative
2                         Web Application Developers
3                      Client Success Representative
4  Junior Technical Support Engineer (fresh gradu...

                  company_name                                  location  \
0                     Deloitte                 Tel Aviv District, Israel
1                          Hud  Tel Aviv-Yafo, Tel Aviv District, Israel
2  GoodWork Environmental Jobs          Or Akiva, Haifa District, Israel
3                    Jobgether                                    Israel
4                       OPSWAT      Petah Tikva, Center District, Israel

  time_posted num_applicants  \
0        None           None
1        None           None
2        None  53 applicants
3        None  51 applicants
4        None           None

                                    description_text  \
0  Deloitte is looking for Financial Analyst. Ove...
1  Job Description\nAbout The Role\nHud is lookin...
2  Web application development\nPosition:\nWeb Ap...
3  This position is posted by Jobgether on behalf...
4  OPSWAT, a global leader in IT, OT, and ICS cri...

                                                 URL search_date
0  https://www.linkedin.com/jobs-guest/jobs/api/j...  2026-03-11
1  https://www.linkedin.com/jobs-guest/jobs/api/j...  2026-03-11
2  https://www.linkedin.com/jobs-guest/jobs/api/j...  2026-03-11
3  https://www.linkedin.com/jobs-guest/jobs/api/j...  2026-03-11
4  https://www.linkedin.com/jobs-guest/jobs/api/j...  2026-03-11

In [11]:
jobs_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 302 entries, 0 to 301
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   job_title         302 non-null    object
 1   company_name      302 non-null    object
 2   location          302 non-null    object
 3   time_posted       38 non-null     object
 4   num_applicants    105 non-null    object
 5   description_text  302 non-null    object
 6   URL               302 non-null    object
 7   search_date       302 non-null    object
dtypes: object(8)
memory usage: 19.0+ KB

In [ ]:
import sqlite3
import pandas as pd



# 3. התחברות ל-DB (יוצר את הקובץ אם הוא לא קיים)
conn = sqlite3.connect('linkedin_jobs.db')

# 4. שמירת הנתונים לטבלה בשם 'jobs'
# if_exists='replace' ימחוק את הטבלה הישנה ויצור חדשה עם הנתונים מה-CSV
# אם אתה רוצה להוסיף לקיים, שנה ל-'append'
jobs_df.to_sql('jobs', conn, if_exists='append', index=False)

# 5. סגירת החיבור
conn.close()

In [3]:
import sqlite3
import pandas as pd
conn = sqlite3.connect('linkedin_jobs.db')
df_jobs = pd.read_sql_query("SELECT * FROM jobs", conn)
df_jobs.head()

,job_title,company_name,location,time_posted,num_applicants,description_text,URL,search_date
0,Financial Analyst,Deloitte,"Tel Aviv District, Israel",None,None,Deloitte is looking for Financial Analyst. Ove...,https://www.linkedin.com/jobs-guest/jobs/api/j...,2026-03-11
1,Sales Development Representative,Hud,"Tel Aviv-Yafo, Tel Aviv District, Israel",None,None,Job Description\nAbout The Role\nHud is lookin...,https://www.linkedin.com/jobs-guest/jobs/api/j...,2026-03-11
2,Web Application Developers,GoodWork Environmental Jobs,"Or Akiva, Haifa District, Israel",None,53 applicants,Web application development\nPosition:\nWeb Ap...,https://www.linkedin.com/jobs-guest/jobs/api/j...,2026-03-11
3,Client Success Representative,Jobgether,Israel,None,51 applicants,This position is posted by Jobgether on behalf...,https://www.linkedin.com/jobs-guest/jobs/api/j...,2026-03-11
4,Junior Technical Support Engineer (fresh gradu...,OPSWAT,"Petah Tikva, Center District, Israel",None,None,"OPSWAT, a global leader in IT, OT, and ICS cri...",https://www.linkedin.com/jobs-guest/jobs/api/j...,2026-03-11

In [ ]:
model = SentenceTransformer('all-MiniLM-L6-v2')
try:
    nlp = spacy.load('en_core_web_md')
except:
    spacy.cli.download("en_core_web_md")
    nlp = spacy.load('en_core_web_md')

In [ ]:
df_jobs['embedding'] = None
for  row in jobs_df.iterrows():
        job_desc = row['description_text']
        job_emb = model.encode(job_desc.lower(), convert_to_tensor=True)
        row['embedding'] = job_emb